### ISSUE TITLE
Commit and file with many chunk

### ISSUE THREAD

**Issue by papaDoc** [imoldman/config#4]
Hi,

I was wondering what happen when you commit only some chunk of a file. (Maybe you want the remaining chunk to be added in another commit later on).

The git add at the end of the script will add the complete file. Rhe whitespace modification and also the chunks that were left for the "next" commit.

**Comment by imoldman** [comment]
Actually, it supports partial commit, In script, the codes say,

``` shell
  # since $file in working directory isn't always equal to $file in index, so we backup it
  mv -f "$file" "${file}.save"
```

It means it will backup the files in working tree, and then,

``` shell
 # discard changes in working directory
  git checkout -- "$file"
```

As comments say, It discards the modifications in files in working tree. Now, the file in working tree is equal to the one in index. In other words, the files in working tree only contain the modification that user want to commit.

So it's friendly to partial commit. Thank U!
